### ISSUE TITLE
undefined method `silence_warnings' for ActiveSupport::Deprecation::DeprecationProxy:Class (NoMethodError)

### ISSUE THREAD

**Issue by Ch00k** [cheezy/pretty_face#20]
Trying to run cucumber with pretty_face report produces the following:

```
[ruby-2.0.0-p353]ay@ay-air ~/RubymineProjects/indi_ui_tests $ cucumber --format PrettyFace::Formatter::Html --out testresults/report.html
undefined method `silence_warnings' for ActiveSupport::Deprecation::DeprecationProxy:Class (NoMethodError)
/Users/ay/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-2.3.18/lib/active_support/deprecation.rb:130:in `<class:DeprecationProxy>'
/Users/ay/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-2.3.18/lib/active_support/deprecation.rb:122:in `<module:Deprecation>'
/Users/ay/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-2.3.18/lib/active_support/deprecation.rb:4:in `<module:ActiveSupport>'
/Users/ay/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-2.3.18/lib/active_support/deprecation.rb:3:in `<top (required)>'
/Users/ay/.rvm/gems/ruby-2.0.0-p353/gems/actionpack-2.3.18/lib/action_view.rb:56:in `<top (required)>'
/Users/ay/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/ay/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/ay/.rvm/gems/ruby-2.0.0-p353/gems/pretty_face-0.3/lib/pretty_face/formatter/html.rb:1:in `<top (required)>'
/Users/ay/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
/Users/ay/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
/Users/ay/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
/Users/ay/.rvm/gems/ruby-2.0.0-p353/gems/cucumber-1.3.10/lib/cucumber/constantize.rb:17:in `rescue in constantize'
/Users/ay/.rvm/gems/ruby-2.0.0-p353/gems/cucumber-1.3.10/lib/cucumber/constantize.rb:6:in `constantize'
/Users/ay/.rvm/gems/ruby-2.0.0-p353/gems/cucumber-1.3.10/lib/cucumber/cli/configuration.rb:83:in `formatter_class'
/Users/ay/.rvm/gems/ruby-2.0.0-p353/gems/cucumber-1.3.10/lib/cucumber/cli/configuration.rb:182:in `block in formatters'
/Users/ay/.rvm/gems/ruby-2.0.0-p353/gems/cucumber-1.3.10/lib/cucumber/cli/configuration.rb:178:in `map'
/Users/ay/.rvm/gems/ruby-2.0.0-p353/gems/cucumber-1.3.10/lib/cucumber/cli/configuration.rb:178:in `formatters'
/Users/ay/.rvm/gems/ruby-2.0.0-p353/gems/cucumber-1.3.10/lib/cucumber/cli/configuration.rb:76:in `build_tree_walker'
/Users/ay/.rvm/gems/ruby-2.0.0-p353/gems/cucumber-1.3.10/lib/cucumber/runtime.rb:46:in `run!'
/Users/ay/.rvm/gems/ruby-2.0.0-p353/gems/cucumber-1.3.10/lib/cucumber/cli/main.rb:47:in `execute!'
/Users/ay/.rvm/gems/ruby-2.0.0-p353/gems/cucumber-1.3.10/bin/cucumber:13:in `<top (required)>'
/Users/ay/.rvm/gems/ruby-2.0.0-p353/bin/cucumber:23:in `load'
/Users/ay/.rvm/gems/ruby-2.0.0-p353/bin/cucumber:23:in `<main>'
[ruby-2.0.0-p353]ay@ay-air ~/RubymineProjects/indi_ui_tests $
```

This is reproducible with both Ruby 2.0 and 2.1

**Comment by Rocky2908** [comment]
@Ch00k  what's wrong with ur environment file. I am running ino the same problem
