### ISSUE TITLE
Prettyface out of date with Cucumber

### ISSUE THREAD

**Issue by Paul-Clewell** [cheezy/pretty_face#36]
Hey folks,

This is an issue we're picking up at a client, and after a bit of digging, I've found that the cucumber/ast references within the code is actually causing the project to fail spectacularly.

Not sure how to fix, but I did dig up that Ast was deprecated. Thought I'd point you in the right direction.

C:\Ruby200\bin\ruby.exe -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) C:\Ruby200\bin/cucumber C:/Users/TNV766/Desktop/ICORE_Hispanic_Automation_Subversion/51.05_new/icoreAcceptanceTests/features/Hispanic_TellUs_About_Yourself_Dropdowns.feature --format Teamcity::Cucumber::Formatter --expand --color -r features -p st5 RDEE_BROWSER=firefox
Testing started at 10:28 AM ...
0 scenarios
0 steps
0m0.000s
NaN (ActionView::Template::Error)
C:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-1.3.17/lib/cucumber/formatter/duration.rb:8:in `divmod'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-1.3.17/lib/cucumber/formatter/duration.rb:8:in`format_duration'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/pretty_face-0.10.2/lib/pretty_face/formatter/view_helper.rb:33:in `scenario_average_duration'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/pretty_face-0.10.2/lib/pretty_face/templates/main.erb:53:in`_____uby____lib_ruby_gems_______gems_pretty_face________lib_pretty_face_templates_main_erb___341596305_27652512'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/actionview-4.1.6/lib/action_view/template.rb:145:in `block in render'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/activesupport-4.1.6/lib/active_support/notifications.rb:161:in`instrument'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/actionview-4.1.6/lib/action_view/template.rb:339:in `instrument'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/actionview-4.1.6/lib/action_view/template.rb:143:in`render'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/actionview-4.1.6/lib/action_view/renderer/template_renderer.rb:55:in `block (2 levels) in render_template'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/actionview-4.1.6/lib/action_view/renderer/abstract_renderer.rb:38:in`block in instrument'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `block in instrument'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/activesupport-4.1.6/lib/active_support/notifications/instrumenter.rb:20:in`instrument'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `instrument'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/actionview-4.1.6/lib/action_view/renderer/abstract_renderer.rb:38:in`instrument'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/actionview-4.1.6/lib/action_view/renderer/template_renderer.rb:54:in `block in render_template'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/actionview-4.1.6/lib/action_view/renderer/template_renderer.rb:62:in`render_with_layout'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/actionview-4.1.6/lib/action_view/renderer/template_renderer.rb:53:in `render_template'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/actionview-4.1.6/lib/action_view/renderer/template_renderer.rb:17:in`render'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/actionview-4.1.6/lib/action_view/renderer/renderer.rb:42:in `render_template'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/actionview-4.1.6/lib/action_view/renderer/renderer.rb:23:in`render'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/actionview-4.1.6/lib/action_view/helpers/rendering_helper.rb:32:in `render'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/pretty_face-0.10.2/lib/pretty_face/formatter/html.rb:171:in`generate_report'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/pretty_face-0.10.2/lib/pretty_face/formatter/html.rb:140:in `after_features'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-1.3.17/lib/cucumber/ast/tree_walker.rb:181:in`block in send_to_all'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-1.3.17/lib/cucumber/ast/tree_walker.rb:179:in `each'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-1.3.17/lib/cucumber/ast/tree_walker.rb:179:in`send_to_all'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-1.3.17/lib/cucumber/ast/tree_walker.rb:171:in `broadcast'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-1.3.17/lib/cucumber/ast/tree_walker.rb:20:in`visit_features'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-1.3.17/lib/cucumber/runtime.rb:49:in `run!'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-1.3.17/lib/cucumber/cli/main.rb:47:in`execute!'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-1.3.17/bin/cucumber:13:in `<top (required)>'
C:/Ruby200/bin/cucumber:23:in`load'
C:/Ruby200/bin/cucumber:23:in `<top (required)>'
-e:1:in`load'
-e:1:in `<main>'

Process finished with exit code 1
Empty test suite.

**Comment by mattwynne** [comment]
#35 is related. @cheezy if you'd like some help to get this gem working with Cucumber 2.0 just ping me and we can book some time to pair on it, or figure out how else we can help.

**Comment by JohnSmall** [comment]
I'm seeing this error as well. When I install and run PrettyFace on my laptop it's OK. When it runs on Jenkins I get the error above. 

Locally I have pretty_face (0.10.3) and cucumber (1.3.17), on our Jenkins box its exactly the same. Yet the Jenkins job fails completely and the laptop runs OK.

**Comment by dingokiller** [comment]
Hi @cheezy & @mattwynne. I just took note that @olleolleolle has been working to get Pretty_Face working with Cucumber 2.0.0+ and I was wondering if there is any chance of those changes (or something similar) being merged into master. 

Pretty Face is the best reporting gem by a mile and I would love to see it back up to date.

**Comment by olleolleolle** [comment]
take my changes as dog-slapping-keyboard-until-it-kinda-works, please. 

And, I had to give up, since I knew too little of the upcoming API. 

The work with pretty_face taught me a lot about what a Formatter needs to function.

**Comment by olleolleolle** [comment]
That said, I also dig that more people want a modern pretty_face out there! Yay!

**Comment by mattwynne** [comment]
How can I help?

**Comment by olleolleolle** [comment]
@mattwynne I made a "visualization PR" marked WIP, for the fixing of this thing.

**Comment by pittgoose** [comment]
Looks like there was a fix to handle cucumber 2. Any chance this can get tagged for release so I can pull it with rubygems?

**Comment by timsheng** [comment]
when it will be fixed ?

**Comment by Githraine** [comment]
Hello, can we please have an update on this issue?
Also, what is the latest version combo that does work?
Thank you
Jason Koelewyn

**Comment by tk8817** [comment]
Cucumber 1.3.20 + Latest release of Pretty Face.

If you are feeling inclined, I opened a code bounty which you could contribute to. Having made modifications myself, It is a significant amount of work to upgrade Pretty Face to work with cucumber 2.0

Big thanks to Jeff for all the work he has done so far.
