### ISSUE TITLE
PrettyFace Does not work with latest version of ActionPack (4.2.0)

### ISSUE THREAD

**Issue by saclark** [cheezy/pretty_face#38]
It looks like using the latest PrettyFace (0.10.3) with the latest ActionPack (4.2.0) causes the html formatter to blow up (stack trace below). Temporary fix is to use ActionPack 4.1.6 with PrettyFace.

```
{:superclass_delegating_accessor=>:class_attribute} is not a symbol (TypeError)
c:/Ruby200/lib/ruby/gems/2.0.0/gems/deprecated-2.0.1/lib/deprecated.rb:176:in `instance_method'
c:/Ruby200/lib/ruby/gems/2.0.0/gems/deprecated-2.0.1/lib/deprecated.rb:176:in `block in <top (required)>'
c:/Ruby200/lib/ruby/gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/core_ext/class/delegating_attributes.rb:26:in `<class:Class>'
c:/Ruby200/lib/ruby/gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/core_ext/class/delegating_attributes.rb:6:in `<top (required)>'
c:/Ruby200/lib/ruby/gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/core_ext/class.rb:2:in `require'
c:/Ruby200/lib/ruby/gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/core_ext/class.rb:2:in `<top (required)>'
c:/Ruby200/lib/ruby/gems/2.0.0/gems/actionview-4.2.0/lib/action_view/template/resolver.rb:2:in `require'
c:/Ruby200/lib/ruby/gems/2.0.0/gems/actionview-4.2.0/lib/action_view/template/resolver.rb:2:in `<top (required)>'
c:/Ruby200/lib/ruby/gems/2.0.0/gems/actionview-4.2.0/lib/action_view/lookup_context.rb:4:in `require'
c:/Ruby200/lib/ruby/gems/2.0.0/gems/actionview-4.2.0/lib/action_view/lookup_context.rb:4:in `<top (required)>'
c:/Ruby200/lib/ruby/gems/2.0.0/gems/actionview-4.2.0/lib/action_view/base.rb:8:in `require'
c:/Ruby200/lib/ruby/gems/2.0.0/gems/actionview-4.2.0/lib/action_view/base.rb:8:in `<top (required)>'
c:/Ruby200/lib/ruby/gems/2.0.0/gems/pretty_face-0.10.3/lib/pretty_face/formatter/html.rb:159:in `generate_report'
c:/Ruby200/lib/ruby/gems/2.0.0/gems/pretty_face-0.10.3/lib/pretty_face/formatter/html.rb:130:in `after_features'
c:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-1.3.18/lib/cucumber/ast/tree_walker.rb:181:in `block in send_to_all'
c:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-1.3.18/lib/cucumber/ast/tree_walker.rb:179:in `each'
c:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-1.3.18/lib/cucumber/ast/tree_walker.rb:179:in `send_to_all'
c:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-1.3.18/lib/cucumber/ast/tree_walker.rb:171:in `broadcast'
c:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-1.3.18/lib/cucumber/ast/tree_walker.rb:20:in `visit_features'
c:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-1.3.18/lib/cucumber/runtime.rb:49:in `run!'
c:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-1.3.18/lib/cucumber/cli/main.rb:47:in `execute!'
c:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-1.3.18/bin/cucumber:13:in `<top (required)>'
c:/Ruby200/bin/cucumber:23:in `load'
c:/Ruby200/bin/cucumber:23:in `<main>'
```

**Comment by Githraine** [comment]
+1

**Comment by vinaykandragula** [comment]
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: actionpack requires activesupport (= 4.1.8),actionview(=4.1.8)

I get the above error when installing pretty_face gem. Can you help?
