### ISSUE TITLE
"cannot load such file -- cucumber/ast/scenario" error is getting when i tried to use pretty face gem in my profiles 'default: FIG_NEWTON_FILE=default.yml --format PrettyFace::Formatter::Html --out results/index.html browser=firefox'

### ISSUE THREAD

**Issue by Radhakrishna-N** [cheezy/pretty_face#39]
cannot load such file -- cucumber/ast/scenario
Error creating formatter: PrettyFace::Formatter::Html (LoadError)
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/pretty_face-0.10.3/lib/pretty_face/formatter/html.rb:5:in `<top (required)>'
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/cucumber-2.0.0/lib/cucumber/constantize.rb:17:in `rescue in constantize'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/cucumber-2.0.0/lib/cucumber/constantize.rb:6:in `constantize'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/cucumber-2.0.0/lib/cucumber/cli/configuration.rb:73:in `formatter_class'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/cucumber-2.0.0/lib/cucumber/cli/configuration.rb:172:in `block in formatter_factories'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/cucumber-2.0.0/lib/cucumber/cli/configuration.rb:168:in `map'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/cucumber-2.0.0/lib/cucumber/cli/configuration.rb:168:in `formatter_factories'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/cucumber-2.0.0/lib/cucumber/runtime.rb:193:in `formatters'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/cucumber-2.0.0/lib/cucumber/runtime.rb:185:in `report'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/cucumber-2.0.0/lib/cucumber/runtime.rb:67:in `run!'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/cucumber-2.0.0/lib/cucumber/cli/main.rb:38:in `execute!'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/cucumber-2.0.0/bin/cucumber:9:in `<top (required)>'
C:/Ruby193/bin/cucumber:23:in `load'
C:/Ruby193/bin/cucumber:23:in `<main>'

Can anyone please help me to resolve it?

I am using below versions
- RUBY  Version 1.9.3
- Cucumber version 2.0.0
- Pretty_face version 0.10.3

Thanks.

**Comment by vanatomas** [comment]
Why is this closed? #40 still in progress, I have same problem still. Using Rubymine with latest versions

**Comment by shanakafernando** [comment]
Still I'm experiencing this issue

**Comment by mupcakes** [comment]
Still having this issue myself, for about 2 years or so now.

**Comment by Startouf** [comment]
Yep, confirmed

**Comment by christianbaumann** [comment]
Also experiencing it
