### ISSUE TITLE
cannot load such file -- cucumber/ast/scenario

### ISSUE THREAD

**Issue by vanatomas** [cheezy/pretty_face#41]
error that I get

cannot load such file -- cucumber/ast/scenario
Error creating formatter: PrettyFace::Formatter::Html (LoadError)
/Users/dennisdem/.rvm/gems/ruby-2.2.1/gems/pretty_face-0.10.3/lib/pretty_face/formatter/html.rb:5:in `require'
/Users/dennisdem/.rvm/gems/ruby-2.2.1/gems/pretty_face-0.10.3/lib/pretty_face/formatter/html.rb:5:in `<top (required)>'
/Users/dennisdem/.rvm/gems/ruby-2.2.1/gems/cucumber-2.0.0/lib/cucumber/constantize.rb:17:in `require'
/Users/dennisdem/.rvm/gems/ruby-2.2.1/gems/cucumber-2.0.0/lib/cucumber/constantize.rb:17:in `rescue in constantize'
/Users/dennisdem/.rvm/gems/ruby-2.2.1/gems/cucumber-2.0.0/lib/cucumber/constantize.rb:6:in `constantize'
/Users/dennisdem/.rvm/gems/ruby-2.2.1/gems/cucumber-2.0.0/lib/cucumber/cli/configuration.rb:73:in `formatter_class'
/Users/dennisdem/.rvm/gems/ruby-2.2.1/gems/cucumber-2.0.0/lib/cucumber/cli/configuration.rb:172:in `block in formatter_factories'
/Users/dennisdem/.rvm/gems/ruby-2.2.1/gems/cucumber-2.0.0/lib/cucumber/cli/configuration.rb:168:in `map'
/Users/dennisdem/.rvm/gems/ruby-2.2.1/gems/cucumber-2.0.0/lib/cucumber/cli/configuration.rb:168:in `formatter_factories'
/Users/dennisdem/.rvm/gems/ruby-2.2.1/gems/cucumber-2.0.0/lib/cucumber/runtime.rb:193:in `formatters'
/Users/dennisdem/.rvm/gems/ruby-2.2.1/gems/cucumber-2.0.0/lib/cucumber/runtime.rb:185:in `report'
/Users/dennisdem/.rvm/gems/ruby-2.2.1/gems/cucumber-2.0.0/lib/cucumber/runtime.rb:67:in `run!'
/Users/dennisdem/.rvm/gems/ruby-2.2.1/gems/cucumber-2.0.0/lib/cucumber/cli/main.rb:38:in `execute!'
/Users/dennisdem/.rvm/gems/ruby-2.2.1/gems/cucumber-2.0.0/bin/cucumber:9:in `<top (required)>'
/Users/dennisdem/.rvm/gems/ruby-2.2.1/bin/cucumber:23:in `load'
/Users/dennisdem/.rvm/gems/ruby-2.2.1/bin/cucumber:23:in `<top (required)>'
-e:1:in `load'
-e:1:in `<main>'

Running Rubymine 

Using cucumber 2.0.0
Using pretty_face 0.10.3
Using rspec 3.2.0
Using selenium-webdriver 2.46.2

**Comment by shanakadev** [comment]
I'm also getting the same error, did anybody find a solution to this?

**Comment by cheyane** [comment]
any update on this issue?

**Comment by vveliev** [comment]
I think it need's to be reliased

**Comment by cheezy** [comment]
I am working on pretty_face update right now.  I hope to have a functioning release out soon.

**Comment by anilreddy** [comment]
Thanks @cheezy thats a great news..!!

**Comment by aMilyukov** [comment]
I am having the issue also.

**Comment by tomatobrown** [comment]
after this is fixed it might be a good time for a new release

**Comment by vanatomas** [comment]
any updates on this one?

**Comment by samuel012** [comment]
any news sir @cheezy ?

**Comment by kkrishan** [comment]
Hi all , any updates/work arounds on this issue ? I have looked into options : 1 downgrade cucumber 2. Allure  3. reportbuilder . Any more  suggestions .

**Comment by ktyagi** [comment]
I am also facing same issue.Did anybody find any solution ?

**Comment by ghost** [comment]
could you take me off the list?

**Comment by harimadusumilli** [comment]
Has anyone been able to find a solution to the issue with pretty face :
cannot load such file -- cucumber/ast/scenario (LoadError)
C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/pretty_face-0.10.3/lib/pretty_face/formatter/html.rb:5:i
C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/pretty_face-0.10.3/lib/pretty_face.rb:2:in `<top (requir
C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
C:/Work/FMS-Automation/features/support/hooks.rb:2:in `<top (required)>'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:142:
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:84:i
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:i
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:i
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:253:in `load_step
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:61:in `run!'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:32:in `execute!'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-2.4.0/bin/cucumber:8:in `<top (required)>'

**Comment by mupcakes** [comment]
I guess this has been left for dead and to rot..

**Comment by mupcakes** [comment]
Guess after 2 years it won't get fixed...time to move on...
has been unusable for years for me now

**Comment by mirelon** [comment]
Tried to use this gem. Had to remove it because this issue makes it unusable.
